name: glacier-dev
services:
  transmission:
    container_name: "transmission-dev"
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - USER=admin
      - PASS=admin
    volumes:
      - .build/transmission/config:/config
      - /home/ra341/Dev/Go/glacier/.build/dev/incomplete:/home/ra341/Dev/Go/glacier/.build/dev/incomplete
    ports:
      - "9091:9091"
