name: Comment on Label

on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [ labeled ]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment based on label
        uses: actions/github-script@v7
        with:
          script: |
            const label = context.payload.label.name;
            let comment = '';
            
            console.log(label)
            
            if (label === 'done') {
              comment = [
                  '✅ This issue has been implemented in the canary build!',
                  '',
                  'You can test it by running:',
                  '```bash',
                  'docker run --rm -p 8866:8866 -e DOCKMAN_LOG_AUTH_WARNING=false -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/ra341/dockman:canary',
                  '```',
                  '',
                  'Please share any feedback or issues you encounter.',
                  '',
                  '⚠️ **Note:** Canary builds are unstable and may contain breaking changes.',
                ].join('\n');
            }

            if (comment) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
